# Generated by Django 6.0.5 on 2026-05-26 08:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('USUARIO', 'Billetera de Usuario'), ('CASA', 'Cuenta Matriz de la Casa'), ('PENDIENTES', 'Apuestas Pendientes (Escrow)'), ('BONOS', 'Fondo de Bonos')], default='USUARIO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billetera', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('direccion', models.CharField(choices=[('DEBIT', 'Débito (-)'), ('CREDIT', 'Crédito (+)')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18)),
                ('descripcion', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.billetera')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Verificación'), ('VERIFICADO', 'Verificado'), ('BLOQUEADO', 'Bloqueado'), ('AUTOEXCLUIDO', 'Autoexcluido')], default='PENDIENTE', max_length=20)),
                ('limite_deposito_diario', models.DecimalField(decimal_places=4, default=Decimal('1000.0000'), max_digits=18)),
                ('autoexcluido_hasta', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
