# Generated by Django 6.0.5 on 2026-05-26 08:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(choices=[('LOCAL', 'Gana Local'), ('EMPATE', 'Empate'), ('VISITANTE', 'Gana Visitante')], max_length=20)),
                ('monto_apostado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('cuota_fijada', models.DecimalField(decimal_places=2, help_text='La cuota exacta que compró el usuario en el momento de apostar.', max_digits=6)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('ganancia_potencial', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuestas', to='deportes.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
