# Generated by Django 6.0.5 on 2026-05-24 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=100, verbose_name='Equipo Local')),
                ('equipo_visitante', models.CharField(max_length=100, verbose_name='Equipo Visitante')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Partido')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de inicio'), ('EN_JUEGO', 'En Juego (En vivo)'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Evento Deportivo',
                'verbose_name_plural': 'Eventos Deportivos',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paga_local', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Cuota Local (1)')),
                ('paga_empate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Cuota Empate (X)')),
                ('paga_visitante', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Cuota Visitante (2)')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='deportes.evento')),
            ],
            options={
                'verbose_name': 'Cuota del Evento',
                'verbose_name_plural': 'Cuotas de los Eventos',
            },
        ),
    ]
