# Generated by Django 6.0.5 on 2026-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='deporte',
            field=models.CharField(choices=[('FUTBOL', '⚽ Fútbol'), ('BASKET', '🏀 Baloncesto'), ('TENIS', '🎾 Tenis'), ('ESPORTS', '🎮 eSports'), ('UFC', '🥊 UFC / Boxeo')], default='FUTBOL', max_length=20),
        ),
    ]
